/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crearuimodificador;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Paco G
 */
public class ModificadorUi extends javax.swing.JFrame {

    /**
     * Creates new form ModificadorUi
     */
    public ModificadorUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkSimple = new javax.swing.JCheckBox();
        checkVehiculos = new javax.swing.JCheckBox();
        checkHdhq4 = new javax.swing.JCheckBox();
        checkBrass = new javax.swing.JCheckBox();
        checkJunction = new javax.swing.JCheckBox();
        checkHdhq2 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        addBoton = new javax.swing.JButton();
        cancelBoton = new javax.swing.JButton();
        checkTraduccion = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        textDirectorio = new javax.swing.JTextField();
        botonDirectorio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AÑADIENDO MODIFICADORES");

        checkSimple.setText("Simple UI");
        checkSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSimpleActionPerformed(evt);
            }
        });

        checkVehiculos.setText("Vehículos más rápidos");

        checkHdhq4.setText("HDHQ 4K Texturas");

        checkBrass.setText("Cobre y Zinc para hacer Brass");

        checkJunction.setText("Junction Box");

        checkHdhq2.setText("HDHQ 2K Texturas");

        jLabel1.setText("Selecciona las modificaciones que quieres añadir al juego.");

        addBoton.setText("AÑADIR");
        addBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBotonActionPerformed(evt);
            }
        });

        cancelBoton.setText("CANCELAR");
        cancelBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBotonActionPerformed(evt);
            }
        });

        checkTraduccion.setText("Traducción al español (proximamente)");
        checkTraduccion.setEnabled(false);

        jLabel2.setBackground(new java.awt.Color(100, 100, 100));
        jLabel2.setText("Versión Alpha 17.1 Estable");

        textDirectorio.setText("C:\\Program Files (x86)\\Steam\\steamapps\\common\\7 Days To Die");

        botonDirectorio.setText("Seleccionar");
        botonDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDirectorioActionPerformed(evt);
            }
        });

        jLabel3.setText("Selecciona la carpeta de instalación del juego");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkJunction)
                                    .addComponent(checkHdhq2)
                                    .addComponent(checkSimple)
                                    .addComponent(checkVehiculos)
                                    .addComponent(checkHdhq4)
                                    .addComponent(checkBrass)
                                    .addComponent(checkTraduccion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cancelBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonDirectorio))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDirectorio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSimple)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkVehiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkHdhq4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkHdhq2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkJunction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBrass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkTraduccion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBoton)
                    .addComponent(cancelBoton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDirectorioActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.showOpenDialog(null);
        File f=chooser.getCurrentDirectory();
        String directorio=f.getAbsolutePath();
        textDirectorio.setText(directorio);
    }//GEN-LAST:event_botonDirectorioActionPerformed

    private void checkSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSimpleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkSimpleActionPerformed

    private void cancelBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBotonActionPerformed
        
            System.exit(0);
        
    }//GEN-LAST:event_cancelBotonActionPerformed

    private void addBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBotonActionPerformed
        if (checkSimple.isSelected()==true) {
            try {
                InstalarSimple();
            } catch (IOException ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkSimple.setSelected(false);
            checkSimple.setEnabled(false);
        } 
        if (checkVehiculos.isSelected()==true) {
            InstalarVehiculos();
            checkVehiculos.setSelected(false);
            checkVehiculos.setEnabled(false);
        } 
        if (checkHdhq4.isSelected()==true) {
            InstalarHdhq4();
            checkHdhq4.setSelected(false);
            checkHdhq4.setEnabled(false);
        } 
        if (checkHdhq2.isSelected()==true) {
            InstalarHdhq2();
            checkHdhq2.setSelected(false);
            checkHdhq2.setEnabled(false);
        } 
        if (checkJunction.isSelected()==true) {
            InstalarJunction();
            checkJunction.setSelected(false);
            checkJunction.setEnabled(false);
        } 
        if (checkBrass.isSelected()==true) {
            InstalarBrass();
            checkBrass.setSelected(false);
            checkBrass.setEnabled(false);
        } 
        if (checkTraduccion.isSelected()==true) {
            InstalarTraduccion();
            checkTraduccion.setSelected(false);
            checkTraduccion.setEnabled(false);
        }  
    }//GEN-LAST:event_addBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void InstalarSimple() throws IOException{
        System.out.println("Instalando Simple UI");    
        String simple="simple";
        String path=textDirectorio.getText();
        copy(simple, path);
              
              
    }
    public void InstalarVehiculos(){
              System.out.println("Instalando Mejora velocidad Vehículos");
              
    }
    public void InstalarHdhq4(){
              System.out.println("Instalando HDHQ 4K");
              
    }
    public void InstalarHdhq2(){
              System.out.println("Instalando HDHQ 2K");
              
    }
    public void InstalarJunction(){
              System.out.println("Instalando Junction Box");
              
    }
    public void InstalarBrass(){
              System.out.println("Instalando Craft Brass");
              
    }
    public void InstalarTraduccion(){
              System.out.println("Instalando Traducción");
              
    }
    public static void copy(File sourceLocation, File targetLocation) throws IOException {
        if (sourceLocation.isDirectory()) {
            copyDirectory(sourceLocation, targetLocation);
        } else {
            copyFile(sourceLocation, targetLocation);
        }
    }
    public static void copy(String sSourceLocation, String stargetLocation) throws IOException {         
         File sourceLocation = new File(sSourceLocation);
         File targetLocation = new File(stargetLocation);

        if (sourceLocation.isDirectory()) { //Es directorio.
            copyDirectory(sourceLocation, targetLocation);
        } else { //Es archivo.
            copyFile(sourceLocation, targetLocation);
        }
    }
    private static void copyDirectory(File source, File target) throws IOException {
        if (!target.exists()) {
            //No existe directorio destino, lo crea.
            target.mkdir();
        }
        for (String f : source.list()) {
            //Copia archivos de directorio fuente a destino.
            copy(new File(source, f), new File(target, f));
        }
    }

    private static void copyFile(File source, File target) throws IOException {
        try (
            InputStream in = new FileInputStream(source);
            OutputStream out = new FileOutputStream(target)) {
            byte[] buffer = new byte[1024];
            int length;
            while ((length = in.read(buffer)) > 0) {
                out.write(buffer, 0, length);
            }
        }
    }
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificadorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificadorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificadorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificadorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificadorUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBoton;
    private javax.swing.JButton botonDirectorio;
    private javax.swing.JButton cancelBoton;
    private javax.swing.JCheckBox checkBrass;
    private javax.swing.JCheckBox checkHdhq2;
    private javax.swing.JCheckBox checkHdhq4;
    private javax.swing.JCheckBox checkJunction;
    private javax.swing.JCheckBox checkSimple;
    private javax.swing.JCheckBox checkTraduccion;
    private javax.swing.JCheckBox checkVehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textDirectorio;
    // End of variables declaration//GEN-END:variables
}
