/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crearuimodificador;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Paco G
 */
public class ModificadorUi extends javax.swing.JFrame {

    /**
     * Creates new form ModificadorUi
     */
    public ModificadorUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkSimple = new javax.swing.JCheckBox();
        checkVehiculos = new javax.swing.JCheckBox();
        checkAcero = new javax.swing.JCheckBox();
        checkBrass = new javax.swing.JCheckBox();
        checkJunction = new javax.swing.JCheckBox();
        checkCarbon = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        addBoton = new javax.swing.JButton();
        cancelBoton = new javax.swing.JButton();
        checkTraduccion = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        textDirectorio = new javax.swing.JTextField();
        botonDirectorio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AÑADIENDO MODIFICADORES");

        checkSimple.setText("Simple UI");
        checkSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSimpleActionPerformed(evt);
            }
        });

        checkVehiculos.setText("Vehículos más rápidos");
        checkVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVehiculosActionPerformed(evt);
            }
        });

        checkAcero.setText("17.0 Acero a lvl35");
        checkAcero.setToolTipText("");

        checkBrass.setText("Cobre y Zinc para hacer Brass");

        checkJunction.setText("Junction Box");

        checkCarbon.setText("Carbón en hoguera");
        checkCarbon.setToolTipText("");

        jLabel1.setText("Selecciona las modificaciones que quieres añadir al juego.");

        addBoton.setText("AÑADIR");
        addBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBotonActionPerformed(evt);
            }
        });

        cancelBoton.setText("CANCELAR");
        cancelBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBotonActionPerformed(evt);
            }
        });

        checkTraduccion.setText("Traducción al español (proximamente)");
        checkTraduccion.setEnabled(false);

        jLabel2.setBackground(new java.awt.Color(100, 100, 100));
        jLabel2.setText("Versión 1.0");

        textDirectorio.setText("C:\\Program Files (x86)\\Steam\\steamapps\\common\\7 Days To Die");
        textDirectorio.setToolTipText("");
        textDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDirectorioActionPerformed(evt);
            }
        });

        botonDirectorio.setText("Seleccionar");
        botonDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDirectorioActionPerformed(evt);
            }
        });

        jLabel3.setText("Selecciona la carpeta de instalación del juego");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkJunction)
                                    .addComponent(checkCarbon)
                                    .addComponent(checkSimple)
                                    .addComponent(checkVehiculos)
                                    .addComponent(checkAcero)
                                    .addComponent(checkBrass))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(textDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(botonDirectorio))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(37, 37, 37))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkTraduccion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDirectorio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSimple)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkVehiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkAcero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkCarbon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkJunction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBrass)
                .addGap(18, 18, 18)
                .addComponent(checkTraduccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBoton)
                    .addComponent(cancelBoton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDirectorioActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.showOpenDialog(null);
        File f=chooser.getCurrentDirectory();
        String directorio=f.getAbsolutePath();
        textDirectorio.setText(directorio);
    }//GEN-LAST:event_botonDirectorioActionPerformed

    private void checkSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSimpleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkSimpleActionPerformed

    private void cancelBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBotonActionPerformed
        
            System.exit(0);
        
    }//GEN-LAST:event_cancelBotonActionPerformed

    private void addBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBotonActionPerformed
        if (checkSimple.isSelected()==true) {
            try {
                InstalarSimple();
            } catch (IOException ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkSimple.setSelected(false);
            checkSimple.setEnabled(false);
        } 
        if (checkVehiculos.isSelected()==true) {
            try {
                InstalarVehiculos();
            } catch (IOException ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkVehiculos.setSelected(false);
            checkVehiculos.setEnabled(false);
        } 
        if (checkAcero.isSelected()==true) {
            try {
                InstalarAcero();
            } catch (IOException ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkAcero.setSelected(false);
            checkAcero.setEnabled(false);
        } 
        if (checkCarbon.isSelected()==true) {
            try {
                InstalarCarbon();
            } catch (IOException ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkCarbon.setSelected(false);
            checkCarbon.setEnabled(false);
        } 
        if (checkJunction.isSelected()==true) {
            try {
                InstalarJunction();
            } catch (IOException ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkJunction.setSelected(false);
            checkJunction.setEnabled(false);
        } 
        if (checkBrass.isSelected()==true) {
            try {
                InstalarBrass();
            } catch (IOException ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkBrass.setSelected(false);
            checkBrass.setEnabled(false);
        } 
        if (checkTraduccion.isSelected()==true) {
            InstalarTraduccion();
            checkTraduccion.setSelected(false);
            checkTraduccion.setEnabled(false);
        }  
    }//GEN-LAST:event_addBotonActionPerformed

    private void textDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDirectorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDirectorioActionPerformed

    private void checkVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkVehiculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public void InstalarSimple() throws IOException, Exception{
        System.out.println("Instalando Simple UI");    
        descargaMods.DescargaMod("simple");
        String origen="c:/simple";
        String destino=textDirectorio.getText();
        copy(origen, destino);  
        File f= new File(origen);
            //Intentando borrar la carpeta
             funcionEliminarCarpeta1 (f);
            //Hasta aqui el borrar la carpeta
    
        System.out.println("El Mod del brass ha sido instalado");
              
              
    }
    public void InstalarVehiculos() throws IOException, Exception{
        System.out.println("Instalando Craft Vehículos");
        descargaMods.DescargaMod("vehiculo");
        String origen="c:/vehiculo";
        String destino=textDirectorio.getText();
        copy(origen, destino);  
        File f= new File(origen);
            //Intentando borrar la carpeta
             funcionEliminarCarpeta1 (f);
            //Hasta aqui el borrar la carpeta
    
        System.out.println("El Mod del brass ha sido instalado");
    }
    public void InstalarAcero() throws IOException, Exception{
        System.out.println("Instalando Mod para hacer acero a lvl 35");
        descargaMods.DescargaMod("PacoG_Mod");
        String origen="c:/acero";
        String destino=textDirectorio.getText();
        copy(origen, destino);
        File f= new File(origen);
            //Intentando borrar la carpeta
             funcionEliminarCarpeta1 (f);
            //Hasta aqui el borrar la carpeta
    
        System.out.println("El Mod del brass ha sido instalado");
    }
    public void InstalarCarbon() throws IOException, Exception{
        System.out.println("Instalando Mod para hacer carbón en la hoguera");
        descargaMods.DescargaMod("carbon");
        String origen="c:/carbon";
        String destino=textDirectorio.getText();
        copy(origen, destino);
        File f= new File(origen);
            //Intentando borrar la carpeta
             funcionEliminarCarpeta1 (f);
            //Hasta aqui el borrar la carpeta
    
        System.out.println("El Mod del brass ha sido instalado");
    }
    public void InstalarJunction() throws IOException, Exception{
        System.out.println("Instalando Craft Junction");
        descargaMods.DescargaMod("junction");
        String origen="c:/junction";
        String destino=textDirectorio.getText();
        copy(origen, destino);  
        File f= new File(origen);
            //Intentando borrar la carpeta
             funcionEliminarCarpeta1 (f);
            //Hasta aqui el borrar la carpeta
    
        System.out.println("El Mod del brass ha sido instalado");      
    }
    public void InstalarBrass() throws IOException, Exception{
        System.out.println("Instalando Craft Brass");
        descargaMods.DescargaMod("brass");
        String origen="c:/brass";
        String destino=textDirectorio.getText();
        copy(origen, destino);  
        File f= new File(origen);
            //Intentando borrar la carpeta
             funcionEliminarCarpeta1 (f);
            //Hasta aqui el borrar la carpeta
    
        System.out.println("El Mod del brass ha sido instalado");
    }
    public void InstalarTraduccion(){
        System.out.println("Instalando Traducción");
              
    }
    public static void funcionEliminarCarpeta1(File pArchivo) { 
                if (!pArchivo.exists()) { return; } 

                if (pArchivo.isDirectory()) { 
                    for (File f : pArchivo.listFiles()) { 
                        funcionEliminarCarpeta1(f);  } 
                } 
                pArchivo.delete(); 
                }
    public static void copy(File sourceLocation, File targetLocation) throws IOException {
        if (sourceLocation.isDirectory()) {
            copyDirectory(sourceLocation, targetLocation);
        } else {
            copyFile(sourceLocation, targetLocation);
        }
    }
    public static void copy(String sSourceLocation, String stargetLocation) throws IOException {         
         File sourceLocation = new File(sSourceLocation);
         File targetLocation = new File(stargetLocation);

        if (sourceLocation.isDirectory()) { //Es directorio.
            copyDirectory(sourceLocation, targetLocation);
        } else { //Es archivo.
            copyFile(sourceLocation, targetLocation);
        }
    }
    private static void copyDirectory(File source, File target) throws IOException {
        if (!target.exists()) {
            //No existe directorio destino, lo crea.
            target.mkdir();
        }
        for (String f : source.list()) {
            //Copia archivos de directorio fuente a destino.
            copy(new File(source, f), new File(target, f));
        }
    }

    private static void copyFile(File source, File target) throws IOException {
        try (
            InputStream in = new FileInputStream(source);
            OutputStream out = new FileOutputStream(target)) {
            byte[] buffer = new byte[1024];
            int length;
            while ((length = in.read(buffer)) > 0) {
                out.write(buffer, 0, length);
            }
        }
    }
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificadorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificadorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificadorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificadorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificadorUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBoton;
    private javax.swing.JButton botonDirectorio;
    private javax.swing.JButton cancelBoton;
    private javax.swing.JCheckBox checkAcero;
    private javax.swing.JCheckBox checkBrass;
    private javax.swing.JCheckBox checkCarbon;
    private javax.swing.JCheckBox checkJunction;
    private javax.swing.JCheckBox checkSimple;
    private javax.swing.JCheckBox checkTraduccion;
    private javax.swing.JCheckBox checkVehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textDirectorio;
    // End of variables declaration//GEN-END:variables
}
