/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crearuimodificador;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Paco G
 */
public class ModificadorUi extends javax.swing.JFrame {

    /**
     * Creates new form ModificadorUi
     */
    public ModificadorUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkSimple = new javax.swing.JCheckBox();
        checkVehiculos = new javax.swing.JCheckBox();
        checkAcero = new javax.swing.JCheckBox();
        checkBrass = new javax.swing.JCheckBox();
        checkJunction = new javax.swing.JCheckBox();
        checkCarbon = new javax.swing.JCheckBox();
        checkTraduccion = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textDirectorio = new javax.swing.JTextField();
        botonDirectorio = new javax.swing.JButton();
        addBoton = new javax.swing.JButton();
        cancelBoton = new javax.swing.JButton();
        texto = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textoAyuda = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AÑADIENDO MODIFICADORES");

        checkSimple.setText("Simple UI");
        checkSimple.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        checkSimple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkSimpleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkSimpleMouseExited(evt);
            }
        });
        checkSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSimpleActionPerformed(evt);
            }
        });

        checkVehiculos.setText("Vehículos más rápidos");
        checkVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkVehiculosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkVehiculosMouseExited(evt);
            }
        });
        checkVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVehiculosActionPerformed(evt);
            }
        });

        checkAcero.setText("17.0 Acero a lvl35");
        checkAcero.setToolTipText("");
        checkAcero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkAceroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkAceroMouseExited(evt);
            }
        });

        checkBrass.setText("Cobre y Zinc para hacer Brass");
        checkBrass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkBrassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkBrassMouseExited(evt);
            }
        });

        checkJunction.setText("Junction Box");
        checkJunction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkJunctionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkJunctionMouseExited(evt);
            }
        });

        checkCarbon.setText("Carbón en hoguera y Ácido en E. de Química");
        checkCarbon.setToolTipText("");
        checkCarbon.setActionCommand("Carbón en hoguera y Ácido en E. de Química");
        checkCarbon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkCarbonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkCarbonMouseExited(evt);
            }
        });

        checkTraduccion.setText("Traducción al español (proximamente)");
        checkTraduccion.setEnabled(false);
        checkTraduccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkTraduccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkTraduccionMouseExited(evt);
            }
        });

        jLabel1.setText("Selecciona las modificaciones que quieres añadir al juego.");

        jLabel2.setBackground(new java.awt.Color(100, 100, 100));
        jLabel2.setText("Versión 1.0");

        jLabel3.setText("Selecciona la carpeta de instalación del juego");

        textDirectorio.setText("C:\\Program Files (x86)\\Steam\\steamapps\\common\\7 Days To Die");
        textDirectorio.setToolTipText("");
        textDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDirectorioActionPerformed(evt);
            }
        });

        botonDirectorio.setText("Seleccionar");
        botonDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDirectorioActionPerformed(evt);
            }
        });

        addBoton.setText("AÑADIR");
        addBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBotonActionPerformed(evt);
            }
        });

        cancelBoton.setText("CANCELAR");
        cancelBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBotonActionPerformed(evt);
            }
        });

        texto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("AYUDA:");

        textoAyuda.setEditable(false);
        textoAyuda.setColumns(20);
        textoAyuda.setLineWrap(true);
        textoAyuda.setRows(5);
        textoAyuda.setText("Pasa el cursor sobre el Mod y verás aquí una ayudita.");
        textoAyuda.setWrapStyleWord(true);

        javax.swing.GroupLayout textoLayout = new javax.swing.GroupLayout(texto);
        texto.setLayout(textoLayout);
        textoLayout.setHorizontalGroup(
            textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(textoLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textoAyuda))
                .addContainerGap())
        );
        textoLayout.setVerticalGroup(
            textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textoLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cancelBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkJunction)
                            .addComponent(checkCarbon)
                            .addComponent(checkSimple)
                            .addComponent(checkVehiculos)
                            .addComponent(checkAcero)
                            .addComponent(checkBrass)
                            .addComponent(checkTraduccion)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(95, 95, 95)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(textDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(botonDirectorio))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(37, 37, 37))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonDirectorio))
                        .addGap(18, 18, 18)
                        .addComponent(checkSimple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkVehiculos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkAcero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkCarbon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkJunction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkBrass)
                        .addGap(18, 18, 18)
                        .addComponent(checkTraduccion))
                    .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBoton)
                    .addComponent(cancelBoton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDirectorioActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.showOpenDialog(null);
        File f=chooser.getCurrentDirectory();
        String directorio=f.getAbsolutePath();
        textDirectorio.setText(directorio);
    }//GEN-LAST:event_botonDirectorioActionPerformed

    private void checkSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSimpleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkSimpleActionPerformed

    private void cancelBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBotonActionPerformed
        
            System.exit(0);
        
    }//GEN-LAST:event_cancelBotonActionPerformed

    private void addBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBotonActionPerformed
        if (checkSimple.isSelected()==true) {
            try {
                InstalarSimple();
            } catch (IOException ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkSimple.setSelected(false);
            checkSimple.setEnabled(false);
        } 
        if (checkVehiculos.isSelected()==true) {
            try {
                InstalarVehiculos();
            } catch (IOException ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkVehiculos.setSelected(false);
            checkVehiculos.setEnabled(false);
        } 
        if (checkAcero.isSelected()==true) {
            try {
                InstalarAcero();
            } catch (IOException ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkAcero.setSelected(false);
            checkAcero.setEnabled(false);
        } 
        if (checkCarbon.isSelected()==true) {
            try {
                InstalarCarbon();
            } catch (IOException ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkCarbon.setSelected(false);
            checkCarbon.setEnabled(false);
        } 
        if (checkJunction.isSelected()==true) {
            try {
                InstalarJunction();
            } catch (IOException ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkJunction.setSelected(false);
            checkJunction.setEnabled(false);
        } 
        if (checkBrass.isSelected()==true) {
            try {
                InstalarBrass();
            } catch (IOException ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ModificadorUi.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkBrass.setSelected(false);
            checkBrass.setEnabled(false);
        } 
        if (checkTraduccion.isSelected()==true) {
            InstalarTraduccion();
            checkTraduccion.setSelected(false);
            checkTraduccion.setEnabled(false);
        }  
    }//GEN-LAST:event_addBotonActionPerformed

    private void textDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDirectorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDirectorioActionPerformed

    private void checkVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkVehiculosActionPerformed

    private void checkSimpleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkSimpleMouseEntered
        // al pasar el mouse por encima sale un texto de ayuda sobre el Mod
        textoAyuda.setText("Este Mod cambia el Hud de la pantalla del juego añadiendo"
                + " en la parte inferior izquierda sendas barras con la comida y el agua");
    }//GEN-LAST:event_checkSimpleMouseEntered

    private void checkSimpleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkSimpleMouseExited
        // al quitar el mouse de encima desaparece un texto de ayuda sobre el Mod
        textoAyuda.setText("Pasa el cursor sobre el Mod y verás aquí una ayudita.");
    }//GEN-LAST:event_checkSimpleMouseExited

    private void checkVehiculosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkVehiculosMouseEntered
        // TODO add your handling code here:
        textoAyuda.setText("Este Mod cambia la velocidad de los vehículos");
    }//GEN-LAST:event_checkVehiculosMouseEntered

    private void checkVehiculosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkVehiculosMouseExited
        // TODO add your handling code here:
        textoAyuda.setText("Pasa el cursor sobre el Mod y verás aquí una ayudita.");
    }//GEN-LAST:event_checkVehiculosMouseExited

    private void checkAceroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkAceroMouseEntered
        // TODO add your handling code here:
        textoAyuda.setText("Este Mod es exclusivo de la Alpha 17.0 Estable, y lo que hace es"
                + " poder craftear el acero forjado y el crucible a lvl 35");
    }//GEN-LAST:event_checkAceroMouseEntered

    private void checkAceroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkAceroMouseExited
        // TODO add your handling code here:
        textoAyuda.setText("Pasa el cursor sobre el Mod y verás aquí una ayudita.");
    }//GEN-LAST:event_checkAceroMouseExited

    private void checkCarbonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkCarbonMouseEntered
        // TODO add your handling code here:
        textoAyuda.setText("Este Mod (solo testeado en el Alpha 17.0 Estable), y lo que hace es"
                + " poder hacer carbón en la hoguera y ácido en la Estación Química a lvl 10");
    }//GEN-LAST:event_checkCarbonMouseEntered

    private void checkCarbonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkCarbonMouseExited
        // TODO add your handling code here:
        textoAyuda.setText("Pasa el cursor sobre el Mod y verás aquí una ayudita.");
    }//GEN-LAST:event_checkCarbonMouseExited

    private void checkJunctionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkJunctionMouseEntered
        // TODO add your handling code here:
        textoAyuda.setText("Este Mod instala unas cajas (Junction Box), que permiter conexiones sin cables a la vista");
    }//GEN-LAST:event_checkJunctionMouseEntered

    private void checkJunctionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkJunctionMouseExited
        // TODO add your handling code here:
        textoAyuda.setText("Pasa el cursor sobre el Mod y verás aquí una ayudita.");
    }//GEN-LAST:event_checkJunctionMouseExited

    private void checkBrassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBrassMouseEntered
        // TODO add your handling code here:
        textoAyuda.setText("Este Mod permite craftear Brass con dos materiales nuevos, cobre y zinc, así como otros cambios ");
    }//GEN-LAST:event_checkBrassMouseEntered

    private void checkBrassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBrassMouseExited
        // TODO add your handling code here:
        textoAyuda.setText("Pasa el cursor sobre el Mod y verás aquí una ayudita.");
    }//GEN-LAST:event_checkBrassMouseExited

    private void checkTraduccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkTraduccionMouseEntered
        // TODO add your handling code here:
        textoAyuda.setText("Traduce el juego completo al español (PROXIMAMENTE)");
    }//GEN-LAST:event_checkTraduccionMouseEntered

    private void checkTraduccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkTraduccionMouseExited
        // TODO add your handling code here:
        textoAyuda.setText("Pasa el cursor sobre el Mod y verás aquí una ayudita.");
    }//GEN-LAST:event_checkTraduccionMouseExited

    /**
     * @param args the command line arguments
     */
    public void InstalarSimple() throws IOException, Exception{
        System.out.println("Instalando Simple UI");    
        descargaMods.DescargaMod("simple");
        String origen="c:/simple";
        String destino=textDirectorio.getText();
        copy(origen, destino);  
        File f= new File(origen);
            //Intentando borrar la carpeta
             funcionEliminarCarpeta1 (f);
            //Hasta aqui el borrar la carpeta
    
        System.out.println("El Mod del brass ha sido instalado");
              
              
    }
    public void InstalarVehiculos() throws IOException, Exception{
        System.out.println("Instalando Craft Vehículos");
        descargaMods.DescargaMod("vehiculo");
        String origen="c:/vehiculo";
        String destino=textDirectorio.getText();
        copy(origen, destino);  
        File f= new File(origen);
            //Intentando borrar la carpeta
             funcionEliminarCarpeta1 (f);
            //Hasta aqui el borrar la carpeta
    
        System.out.println("El Mod del brass ha sido instalado");
    }
    public void InstalarAcero() throws IOException, Exception{
        System.out.println("Instalando Mod para hacer acero a lvl 35");
        descargaMods.DescargaMod("PacoG_Mod");
        String origen="c:/acero";
        String destino=textDirectorio.getText();
        copy(origen, destino);
        File f= new File(origen);
            //Intentando borrar la carpeta
             funcionEliminarCarpeta1 (f);
            //Hasta aqui el borrar la carpeta
    
        System.out.println("El Mod del brass ha sido instalado");
    }
    public void InstalarCarbon() throws IOException, Exception{
        System.out.println("Instalando Mod para hacer carbón en la hoguera");
        descargaMods.DescargaMod("carbon");
        String origen="c:/carbon";
        String destino=textDirectorio.getText();
        copy(origen, destino);
        File f= new File(origen);
            //Intentando borrar la carpeta
             funcionEliminarCarpeta1 (f);
            //Hasta aqui el borrar la carpeta
    
        System.out.println("El Mod del brass ha sido instalado");
    }
    public void InstalarJunction() throws IOException, Exception{
        System.out.println("Instalando Craft Junction");
        descargaMods.DescargaMod("junction");
        String origen="c:/junction";
        String destino=textDirectorio.getText();
        copy(origen, destino);  
        File f= new File(origen);
            //Intentando borrar la carpeta
             funcionEliminarCarpeta1 (f);
            //Hasta aqui el borrar la carpeta
    
        System.out.println("El Mod del brass ha sido instalado");      
    }
    public void InstalarBrass() throws IOException, Exception{
        System.out.println("Instalando Craft Brass");
        descargaMods.DescargaMod("brass");
        String origen="c:/brass";
        String destino=textDirectorio.getText();
        copy(origen, destino);  
        File f= new File(origen);
            //Intentando borrar la carpeta
             funcionEliminarCarpeta1 (f);
            //Hasta aqui el borrar la carpeta
    
        System.out.println("El Mod del brass ha sido instalado");
    }
    public void InstalarTraduccion(){
        System.out.println("Instalando Traducción");
              
    }
    public static void funcionEliminarCarpeta1(File pArchivo) { 
                if (!pArchivo.exists()) { return; } 

                if (pArchivo.isDirectory()) { 
                    for (File f : pArchivo.listFiles()) { 
                        funcionEliminarCarpeta1(f);  } 
                } 
                pArchivo.delete(); 
                }
    public static void copy(File sourceLocation, File targetLocation) throws IOException {
        if (sourceLocation.isDirectory()) {
            copyDirectory(sourceLocation, targetLocation);
        } else {
            copyFile(sourceLocation, targetLocation);
        }
    }
    public static void copy(String sSourceLocation, String stargetLocation) throws IOException {         
         File sourceLocation = new File(sSourceLocation);
         File targetLocation = new File(stargetLocation);

        if (sourceLocation.isDirectory()) { //Es directorio.
            copyDirectory(sourceLocation, targetLocation);
        } else { //Es archivo.
            copyFile(sourceLocation, targetLocation);
        }
    }
    private static void copyDirectory(File source, File target) throws IOException {
        if (!target.exists()) {
            //No existe directorio destino, lo crea.
            target.mkdir();
        }
        for (String f : source.list()) {
            //Copia archivos de directorio fuente a destino.
            copy(new File(source, f), new File(target, f));
        }
    }

    private static void copyFile(File source, File target) throws IOException {
        try (
            InputStream in = new FileInputStream(source);
            OutputStream out = new FileOutputStream(target)) {
            byte[] buffer = new byte[1024];
            int length;
            while ((length = in.read(buffer)) > 0) {
                out.write(buffer, 0, length);
            }
        }
    }
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificadorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificadorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificadorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificadorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificadorUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBoton;
    private javax.swing.JButton botonDirectorio;
    private javax.swing.JButton cancelBoton;
    private javax.swing.JCheckBox checkAcero;
    private javax.swing.JCheckBox checkBrass;
    private javax.swing.JCheckBox checkCarbon;
    private javax.swing.JCheckBox checkJunction;
    private javax.swing.JCheckBox checkSimple;
    private javax.swing.JCheckBox checkTraduccion;
    private javax.swing.JCheckBox checkVehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textDirectorio;
    private javax.swing.JPanel texto;
    private javax.swing.JTextArea textoAyuda;
    // End of variables declaration//GEN-END:variables
}
